### ISSUE TITLE
failed to read `/.../Cargo.toml` error when cargo build

### ISSUE THREAD

**Issue by s1n7ax** [finnbear/yew_icons#1]
```
cargo --version
cargo 1.59.0 (49d8809dc 2022-02-10)
```

Cargo.toml
```toml
[package]
name = "my-website"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
yew-router = "0.16.0"
yew_icons = {path = "..", features = ["FeatherArrowLeftCircle", "FeatherArrowRightCircle", "FeatherArrowUpCircle"]}
```

Error:
```
➜  my-website git:(main) ✗ cargo build
error: failed to get `yew_icons` as a dependency of package `my-website v0.1.0 (/home/s1n7ax/Workspace/my-website)`

Caused by:
  failed to load source for dependency `yew_icons`

Caused by:
  Unable to update /home/s1n7ax/Workspace

Caused by:
  failed to read `/home/s1n7ax/Workspace/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

**Comment by finnbear** [comment]
Hi there,

I believe the issue is due to directly copying the import statement from the example app's `Cargo.toml` file. As you can see, there is a `path = ".."` attribute, which says that the main repository is one directory above the working directory. This is true for the example code, but **not** for your project. Simply remove `path = ".."` from the import statement, and replace it with `version = "0.1.1"`, so cargo will download the crate from crates.io instead of looking for it where it does not exist :)

I will add a comment to warn against this in the future! (edit: [done](https://github.com/finnbear/yew_icons/commit/50e4ad838bd099924f54dccd27f243814fcc59a8))
